'use strict';
const $=id=>document.getElementById(id);
let csrf='',state=null,filter='all',detailId='',repoVersion=-1,detectVersion=-1,refreshSeq=0,refreshing=false;
const pending=new Set();const secure=location.protocol==='https:';
const preferenceDefaults={refresh:4,direction:'both',interval:3};
const preferenceKey='DantamiRepoSync.preferences.v1';
function normalizePreferences(value){const p=value&&typeof value==='object'?value:{};return{refresh:[0,4,10,30,60].includes(p.refresh)?p.refresh:4,direction:['both','github_to_gitea','gitea_to_github'].includes(p.direction)?p.direction:'both',interval:[1,3,5,15,60,1440].includes(p.interval)?p.interval:3}}
function loadPreferences(){try{return normalizePreferences(JSON.parse(localStorage.getItem(preferenceKey)))}catch{return{...preferenceDefaults}}}
let preferences=loadPreferences(),refreshTimer=null;
function scheduleRefresh(){if(refreshTimer!==null)clearInterval(refreshTimer);refreshTimer=null;if(secure&&preferences.refresh>0)refreshTimer=setInterval(()=>{if(!document.hidden)refresh()},preferences.refresh*1000)}
function fillSettings(p,lang){$('languageSelect').value=lang;$('refreshInterval').value=String(p.refresh);$('defaultDirection').value=p.direction;$('defaultInterval').value=String(p.interval)}
function openSettings(){fillSettings(preferences,document.documentElement.lang==='en'?'en':'ko');clearMessage('settingsMessage');if(!$('settingsModal').open)$('settingsModal').showModal()}
function saveSettings(){
 const lang=$('languageSelect').value,language=window.DantamiLanguage;
 if(pending.size||usersBusy){$('settingsMessage').textContent="Wait for the current request to finish before saving settings.";return}
 if(!language||!language.confirmChange(lang))return;
 const next=normalizePreferences({refresh:Number($('refreshInterval').value),direction:$('defaultDirection').value,interval:Number($('defaultInterval').value)});
 let previous=null;try{previous=localStorage.getItem(preferenceKey);localStorage.setItem(preferenceKey,JSON.stringify(next));if(!language.save(lang))throw Error('cookie')}catch{try{if(previous===null)localStorage.removeItem(preferenceKey);else localStorage.setItem(preferenceKey,previous)}catch{}$('settingsMessage').textContent="Browser storage is blocked. Allow cookies and site storage to save settings.";return}
 preferences=next;scheduleRefresh();$('settingsModal').close();
 if(lang!==language.current){location.reload();return}
 note("Settings saved. Existing repository connections are unchanged.");refresh();
}
const names={idle:"Not checked",healthy:"Healthy",pending:"Changes pending",checking:"Checking",syncing:"Syncing",queued:"Queued",conflict:"Review conflict",error:"Connection error",paused:"Paused"};
const directions={both:"⇄ Bidirectional",github_to_gitea:'→ GitHub → NAS',gitea_to_github:'← NAS → GitHub'};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function note(text,error=false){const open=['users','accounts','add','detail'].find(x=>$(x+'Modal').open);const n=open?$(open==='accounts'?'accountMessage':open+'Message'):$('notice');n.textContent=text;n.className='modal-message '+(error?'error':'ok')}
function clearMessage(id){$(id).textContent='';$(id).className='modal-message'}
function endpoint(action){const u=new URL('index.cgi',location.href);u.searchParams.set('action',action);return u}
async function api(action,body){const o={credentials:'same-origin',cache:'no-store',headers:{}};if(body!==undefined){if(!secure)throw Error("Use the app over HTTPS");o.method='POST';o.headers['Content-Type']='application/json';o.headers['X-CSRF-Token']=csrf;o.body=JSON.stringify(body)}const r=await fetch(endpoint(action),o);if(r.status===401){location.replace('index.cgi');throw Error("Sign in to continue")}let j;try{j=await r.json()}catch{throw Error(r.status===401?"Sign in again with your app account":r.status===403?"Open the app over HTTPS":"Check the app's status in Package Center")}if(!r.ok)throw Error(j.error||"Could not process the request");return j}
function phase(p){return p.archived?'archived':p.busy?p.phase:p.queued?'queued':p.phase||'idle'}
function badge(p){const s=phase(p);return el('span','tag '+s,p.archived?"Archived":names[s]||s)}
function timeText(t){if(!t||t.startsWith('0001'))return "Not yet";return new Date(t).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function isIssue(p){return !!p.error||p.phase==='conflict'||p.phase==='error'}
function button(text,fn,disabled=false,cls=''){const b=el('button',cls,text);b.disabled=disabled;b.addEventListener('click',fn);return b}
function actionButtons(p){const row=el('div','card-actions');const working=p.busy||!!p.queued||pending.has(p.id);if(p.archived){row.append(button("Restore connection",()=>action('restore',{id:p.id}),working||!secure));row.append(button("Remove connection",()=>removePair(p.id),working||!secure,'text-button'));return row}
 row.append(button(p.checked?"Sync now":"Check connection",()=>{if(!state.github_saved||!state.gitea_saved){openAccounts();note("Connect your accounts first");return}action(p.checked?'sync':'check',{id:p.id})},working||!secure,'primary-soft'));
 row.append(button(p.enabled||p.busy||p.queued?"Paused":"Enable automatic sync",()=>action(p.enabled||p.busy||p.queued?'pause':'start',{id:p.id}),pending.has(p.id)||!secure||(!(p.enabled||p.busy||p.queued)&&!p.checked)));
 row.append(button("Details",()=>openDetail(p.id),false,'text-button'));row.append(button("Remove connection",()=>removePair(p.id),working||!secure,'text-button'));return row}
function renderPairs(){if(!state)return;const q=$('search').value.toLowerCase().trim();const list=state.pairs.filter(p=>(filter==='archived'?p.archived:!p.archived)&&(filter!=='active'||p.enabled)&&(filter!=='issues'||isIssue(p))&&(!q||(p.github_repo+' '+p.gitea_repo).toLowerCase().includes(q)));$('pairs').replaceChildren();$('empty').hidden=list.length!==0;
 for(const p of list){const card=el('article','pair-card '+(isIssue(p)?'attention':''));const top=el('div','card-top');top.append(el('span','repo-icon','⌘'),el('h2','',p.github_repo.split('/').pop()),badge(p));card.append(top);const repos=el('div','repo-paths');repos.append(el('p','', 'GitHub  '+p.github_repo),el('p','', 'NAS       '+p.gitea_repo));card.append(repos);const meta=el('div','card-meta');meta.append(el('span','direction',directions[p.direction]),el('span','',p.enabled?"Automatic · "+p.interval+" min":"Automatic sync off"));card.append(meta);
 const status=el('div','card-status');if(p.busy||p.queued){status.append(el('div','activity'),el('span','',p.queued?"Waiting for another repository job to finish":"Processing repository"))}else{status.append(el('span','',p.error||(p.phase==='conflict'?"Changes have diverged. Review the details":p.phase==='pending'?"New changes are ready to sync":p.checked?"Both repositories have been checked":"Start with a connection check")))}card.append(status);const times=el('div','card-times');times.append(el('span','', "Last checked  "+timeText(p.last)));if(p.enabled)times.append(el('span','', "Next check  "+timeText(p.next)));card.append(times,actionButtons(p));$('pairs').append(card)}
}
function draw(s){state=s;csrf=s.csrf;const active=s.pairs.filter(p=>!p.archived);$('countAll').textContent=active.length;$('countHealthy').textContent=active.filter(p=>p.checked&&!p.busy&&!p.queued&&!isIssue(p)&&p.phase==='healthy').length;$('countBusy').textContent=active.filter(p=>p.busy||p.queued).length;$('countIssues').textContent=active.filter(isIssue).length;$('updated').textContent="Last refreshed "+new Date().toLocaleTimeString('en-US');if(s.gitea_user&&!$('accountsModal').open)$('giteaUser').value=s.gitea_user;$('ghState').textContent=s.github_saved?"Token saved":"Not connected";$('gtState').textContent=s.gitea_saved?"Token saved":"Not connected";$('ghState').className='tag '+(s.github_saved?'healthy':'');$('gtState').className='tag '+(s.gitea_saved?'healthy':'');if(s.github_saved)$('gh').placeholder="Saved · enter a token only to replace it";if(s.gitea_saved)$('gt').placeholder="Saved · enter a token only to replace it";$('detectNAS').disabled=!secure||s.detecting||pending.has('detect');$('detectStatus').textContent=s.detect_message||'';if(detectVersion!==(s.detect_version||0)){const first=detectVersion===-1;detectVersion=s.detect_version||0;const list=$('giteaCandidates');list.replaceChildren();for(const c of(s.nas_connections||[])){const o=el('option');o.value=c.url;o.label=c.kind;list.append(o)}if(first)$('giteaEndpoint').value=s.gitea_base||'';else if(!$('accountsModal').open)$('giteaEndpoint').value=s.gitea_base||'';updateTokenLink()}$('save').disabled=!secure||pending.has('save')||s.discovering||s.pairs.some(p=>p.busy||p.queued);$('refreshRepos').disabled=!secure||s.discovering||pending.has('discover')||!s.github_saved||!s.gitea_saved;$('repoListStatus').textContent=s.discovering?"Loading repositories":s.discovery_error||s.discovery_notice||('GitHub '+s.repos.github.length+" · NAS "+s.repos.gitea.length+"");$('addPair').disabled=!secure||pending.has('add')||!$('ghRepo').value||!$('gtRepo').value;if(repoVersion!==s.repo_version){repoVersion=s.repo_version;renderRepoOptions()};renderPairs();if($('detailModal').open)renderDetail(false);if(s.role==='viewer'){for(const id of ['navAccounts','openAdd','navDiagnostics','addPair','save','savePair','archivePair','deletePair']){const n=$(id);if(n)n.disabled=true}for(const b of $('pairs').querySelectorAll('button'))if(b.textContent!=="Details")b.disabled=true}}
function renderRepoOptions(){if(!state)return;for(const [side,prefix]of[['github','gh'],['gitea','gt']]){const list=$(prefix+'Repo'),old=list.value,q=$(prefix+'Filter').value.toLowerCase().trim();list.replaceChildren();const blank=el('option','', "Select a repository");blank.value='';list.append(blank);for(const repo of state.repos[side]){if(q&&!repo.full_name.toLowerCase().includes(q))continue;const used=state.pairs.some(p=>!p.archived&&(side==='github'?p.github_repo:p.gitea_repo).toLowerCase()===repo.full_name.toLowerCase());const o=el('option','',repo.full_name+(used?" · connected":repo.archived?" · read only":''));o.value=repo.full_name;o.disabled=used;list.append(o)}list.value=old;if(list.selectedIndex<0)list.value=''}$('addPair').disabled=!secure||pending.has('add')||!$('ghRepo').value||!$('gtRepo').value}
async function refresh(){if(refreshing)return;refreshing=true;const seq=++refreshSeq;try{const s=await api('status');if(seq===refreshSeq)draw(s)}catch(e){note(e.message,true)}finally{refreshing=false}}
async function action(name,body={}){const key=body.id||name;if(pending.has(key))return false;pending.add(key);refreshSeq++;if(state)draw(state);try{const result=await api(name,body);if(name==='delete'){if($('detailModal').open)$('detailModal').close();note(result.warning||"Connection and local cache removed. Remote repositories are unchanged",!!result.warning)}else if(name==='save'){$('gh').value='';$('gt').value='';note("Tokens saved. Loading repositories")}else if(name==='add'){$('addModal').close();note("Repositories connected. Select Check connection on the card")}else if(name==='update'){note("Settings saved. Check the connection before enabling automatic sync")}else if(name==='archive'){$('detailModal').close();note("Connection archived. Repository code is unchanged")}else{note({check:"Started a check without changing repositories",sync:"Sync requested",start:"Automatic sync enabled",pause:"Pause requested",restore:"Connection restored",discover:"Refreshing repository lists",detect:"Checking Gitea connections on the NAS without sending tokens"}[name]||"Saved")}return true}catch(e){note(e.message,true);return false}finally{pending.delete(key);refreshing=false;await refresh()}}
function openDialog(id){clearMessage(id==='usersModal'?'usersMessage':id==='accountsModal'?'accountMessage':id==='addModal'?'addMessage':'detailMessage');$(id).showModal()}
function openAccounts(){openDialog('accountsModal')}
function openAdd(){if(!state||!state.github_saved||!state.gitea_saved){openAccounts();note("Connect your accounts to select repositories");return}if(!$('addModal').open){$('newDirection').value=preferences.direction;$('newInterval').value=String(preferences.interval);openDialog('addModal')}renderRepoOptions();if(!state.repos.github.length&&!state.discovering)action('discover')}
function openDetail(id){detailId=id;openDialog('detailModal');renderDetail(true)}
function renderDetail(initial){const p=state.pairs.find(x=>x.id===detailId);if(!p){$('detailModal').close();return}$('detailTitle').textContent=p.github_repo.split('/').pop();$('detailStatus').replaceChildren(badge(p),el('span','muted',p.error||"Last checked "+timeText(p.last)));$('detailLinks').replaceChildren();for(const [text,url]of[["GitHub repository ↗",'https://github.com/'+p.github_repo],["NAS repository ↗",(state.gitea_base||'')+'/'+p.gitea_repo]]){const a=el('a','',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';$('detailLinks').append(a)}if(initial){$('editDirection').value=p.direction;$('editInterval').value=String(p.interval)}const locked=p.busy||!!p.queued||p.archived||pending.has(p.id);$('savePair').disabled=locked||!secure;$('editDirection').disabled=locked;$('editInterval').disabled=locked;$('archivePair').disabled=p.busy||!!p.queued||pending.has(p.id)||!secure;$('deletePair').disabled=p.busy||!!p.queued||pending.has(p.id)||!secure;$('archivePair').textContent=p.archived?"Restore connection":"Archive connection";$('detailPlan').replaceChildren();if(!p.plan.length)$('detailPlan').append(el('p','muted',"Run a connection check to see branch and tag results"));for(const r of p.plan){const row=el('div','ref '+r.status);row.append(el('b','',r.ref),el('span','',r.direction),el('p','',r.detail));$('detailPlan').append(row)}$('detailEvents').replaceChildren();for(const e of p.events){const li=el('li');li.append(el('time','',timeText(e.at)),el('span','',e.message));$('detailEvents').append(li)}}
async function diagnostics(){const list=$('diagnosticsResults');list.replaceChildren(el('p','muted',"Checking NAS service status"));$('retryDiagnostics').disabled=true;try{const data=await api('diagnostics');list.replaceChildren();for(const c of data.checks){const row=el('div','ref');row.append(el('b','',c.title),el('span','tag '+(c.ok?'healthy':'error'),c.ok?"Verified":"Needs attention"),el('p','',c.detail));list.append(row)}}catch(e){list.replaceChildren(el('p','error',e.message))}finally{$('retryDiagnostics').disabled=false}}
$('navDiagnostics').addEventListener('click',()=>{$('diagnosticsModal').showModal();diagnostics()});$('retryDiagnostics').addEventListener('click',diagnostics);
$('openAdd').addEventListener('click',openAdd);$('navAccounts').addEventListener('click',openAccounts);$('navDashboard').addEventListener('click',()=>{filter='all';setFilterUI();renderPairs()});$('search').addEventListener('input',renderPairs);
function setFilterUI(){for(const b of document.querySelectorAll('[data-filter]'))b.classList.toggle('selected',b.dataset.filter===filter)}
for(const b of document.querySelectorAll('[data-filter]'))b.addEventListener('click',()=>{filter=b.dataset.filter;setFilterUI();renderPairs()});
for(const b of document.querySelectorAll('dialog .close'))b.addEventListener('click',()=>b.closest('dialog').close());
for(const id of ['ghFilter','gtFilter'])$(id).addEventListener('input',renderRepoOptions);
for(const id of ['ghRepo','gtRepo'])$(id).addEventListener('change',()=>{$('addPair').disabled=!secure||pending.has('add')||!$('ghRepo').value||!$('gtRepo').value});
$('detectNAS').addEventListener('click',()=>action('detect'));
$('refreshRepos').addEventListener('click',()=>action('discover'));
$('save').addEventListener('click',()=>{if(!$('consent').checked){note("Select the consent checkbox to store tokens on the NAS",true);return}action('save',{github_token:$('gh').value.trim(),gitea_token:$('gt').value.trim(),gitea_base:$('giteaEndpoint').value,gitea_user:$('giteaUser').value.trim(),consent:true})});
$('addPair').addEventListener('click',()=>action('add',{github_repo:$('ghRepo').value,gitea_repo:$('gtRepo').value,direction:$('newDirection').value,interval:Number($('newInterval').value)}));
$('savePair').addEventListener('click',()=>action('update',{id:detailId,direction:$('editDirection').value,interval:Number($('editInterval').value)}));
$('archivePair').addEventListener('click',()=>{const p=state.pairs.find(x=>x.id===detailId);if(p)action(p.archived?'restore':'archive',{id:p.id})});
async function boot(){if(!secure){for(const id of ['gh','gt','consent','save'])$(id).disabled=true;note("Open this page over HTTPS",true);return}await refresh();scheduleRefresh()}boot();

function updateTokenLink(){const a=$('giteaTokenLink');try{const u=new URL($('giteaEndpoint').value);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error();u.pathname='/user/settings/applications';a.href=u.href;a.hidden=false}catch{a.removeAttribute('href');a.hidden=true}}
$('giteaEndpoint').addEventListener('input',updateTokenLink);

async function removePair(id){const p=state?.pairs.find(x=>x.id===id);if(!p||p.busy||p.queued||pending.has(id))return;if(!window.confirm("Remove this sync connection?\nGitHub: "+p.github_repo+'\nGitea: '+p.gitea_repo+"\n\nThis deletes the app's connection settings, local cache and check history. GitHub/Gitea repositories are not deleted. Re-adding the connection requires a fresh check without the old deletion history."))return;await action('delete',{id,consent:true})}
$('deletePair').addEventListener('click',()=>removePair(detailId));

let usersBusy=false;
async function loadUsers(){if(state?.role!=='admin')return;const users=await api('auth/users');$('usersList').replaceChildren();for(const u of users){const row=el('div','ref');row.append(el('b','',u.username),el('span','',u.role==='admin'?"Administrator":"Viewer"),el('p','',u.disabled?"Disabled":"Active"));if(u.username!==state.user){row.append(button(u.disabled?"Enable":"Disable",()=>manageUser(u.disabled?'enable':'disable',u.username)));row.append(button("Reset password",()=>manageUser('password',u.username)));row.append(button("Delete account",()=>manageUser('delete',u.username)))}$('usersList').append(row)}}
async function openUsers(){openDialog('usersModal');$('signedIn').textContent=(state?.user||'')+' · '+(state?.role==='admin'?"Administrator":"Viewer");$('adminUserPanel').hidden=state?.role!=='admin';try{await loadUsers()}catch(e){$('usersMessage').textContent=e.message}}
async function manageUser(operation,username){if(usersBusy)return;if(['delete','disable','password'].includes(operation)&&!confirm(username+" account: "+({delete:"Delete",disable:"Disable",password:"Reset password"}[operation])+"? Active sessions will also end."))return;usersBusy=true;try{await api('auth/users',{operation,username,password:$('newUserPassword').value,current_password:$('manageCurrent').value,role:$('newUserRole').value});$('usersMessage').textContent="Account changes saved";await loadUsers()}catch(e){$('usersMessage').textContent=e.message}finally{usersBusy=false;$('manageCurrent').value='';$('newUserPassword').value=''}}
$('navUsers').addEventListener('click',openUsers);
$('logout').addEventListener('click',async()=>{try{await api('auth/logout',{});location.replace('index.cgi')}catch(e){note(e.message,true)}});
$('createUser').addEventListener('click',()=>manageUser('create',$('newUsername').value.trim()));
$('changeOwn').addEventListener('click',async()=>{if(usersBusy)return;if($('ownNew').value!==$('ownConfirm').value){$('usersMessage').textContent="The new passwords do not match";return}usersBusy=true;try{await api('auth/password',{current_password:$('ownCurrent').value,password:$('ownNew').value});location.replace('index.cgi')}catch(e){$('usersMessage').textContent=e.message}finally{usersBusy=false;for(const id of ['ownCurrent','ownNew','ownConfirm'])$(id).value=''}});
$('usersModal').addEventListener('close',()=>{for(const id of ['ownCurrent','ownNew','ownConfirm','manageCurrent','newUserPassword'])$(id).value=''});

$('navSettings').addEventListener('click',openSettings);
$('saveSettings').addEventListener('click',saveSettings);
$('resetSettings').addEventListener('click',()=>{fillSettings(preferenceDefaults,'ko');$('settingsMessage').textContent="Defaults loaded. Select Save settings to apply them."});
$('refreshNow').addEventListener('click',refresh);
window.addEventListener('pageshow',event=>{if(event.persisted){scheduleRefresh();refresh()}});
