'use strict';
const $=id=>document.getElementById(id);
let csrf='',state=null,filter='all',detailId='',repoVersion=-1,detectVersion=-1,refreshSeq=0,refreshing=false;
const pending=new Set();const secure=location.protocol==='https:';
const names={idle:'확인 전',healthy:'정상',pending:'반영 대기',checking:'확인 중',syncing:'동기화 중',queued:'작업 대기',conflict:'충돌 확인',error:'연결 오류',paused:'일시정지'};
const directions={both:'⇄ 양방향',github_to_gitea:'→ GitHub → NAS',gitea_to_github:'← NAS → GitHub'};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function note(text,error=false){const open=['users','accounts','add','detail'].find(x=>$(x+'Modal').open);const n=open?$(open==='accounts'?'accountMessage':open+'Message'):$('notice');n.textContent=text;n.className='modal-message '+(error?'error':'ok')}
function clearMessage(id){$(id).textContent='';$(id).className='modal-message'}
function endpoint(action){const u=new URL('index.cgi',location.href);u.searchParams.set('action',action);return u}
async function api(action,body){const o={credentials:'same-origin',cache:'no-store',headers:{}};if(body!==undefined){if(!secure)throw Error('HTTPS 앱에서 사용해 주세요');o.method='POST';o.headers['Content-Type']='application/json';o.headers['X-CSRF-Token']=csrf;o.body=JSON.stringify(body)}const r=await fetch(endpoint(action),o);if(r.status===401){location.replace('index.cgi');throw Error('로그인이 필요해요')}let j;try{j=await r.json()}catch{throw Error(r.status===401?'앱 계정으로 다시 로그인해 주세요':r.status===403?'HTTPS 앱 화면에서 다시 열어 주세요':'패키지 센터에서 앱 실행 상태를 확인해 주세요')}if(!r.ok)throw Error(j.error||'요청을 처리하지 못했어요');return j}
function phase(p){return p.archived?'archived':p.busy?p.phase:p.queued?'queued':p.phase||'idle'}
function badge(p){const s=phase(p);return el('span','tag '+s,p.archived?'보관됨':names[s]||s)}
function timeText(t){if(!t||t.startsWith('0001'))return '아직 없음';return new Date(t).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function isIssue(p){return !!p.error||p.phase==='conflict'||p.phase==='error'}
function button(text,fn,disabled=false,cls=''){const b=el('button',cls,text);b.disabled=disabled;b.addEventListener('click',fn);return b}
function actionButtons(p){const row=el('div','card-actions');const working=p.busy||!!p.queued||pending.has(p.id);if(p.archived){row.append(button('연결 복원',()=>action('restore',{id:p.id}),working||!secure));row.append(button('연결 제거',()=>removePair(p.id),working||!secure,'text-button'));return row}
 row.append(button(p.checked?'지금 동기화':'연결 확인',()=>{if(!state.github_saved||!state.gitea_saved){openAccounts();note('계정을 먼저 연결해 주세요');return}action(p.checked?'sync':'check',{id:p.id})},working||!secure,'primary-soft'));
 row.append(button(p.enabled||p.busy||p.queued?'일시정지':'자동 실행 켜기',()=>action(p.enabled||p.busy||p.queued?'pause':'start',{id:p.id}),pending.has(p.id)||!secure||(!(p.enabled||p.busy||p.queued)&&!p.checked)));
 row.append(button('상세 보기',()=>openDetail(p.id),false,'text-button'));row.append(button('연결 제거',()=>removePair(p.id),working||!secure,'text-button'));return row}
function renderPairs(){if(!state)return;const q=$('search').value.toLowerCase().trim();const list=state.pairs.filter(p=>(filter==='archived'?p.archived:!p.archived)&&(filter!=='active'||p.enabled)&&(filter!=='issues'||isIssue(p))&&(!q||(p.github_repo+' '+p.gitea_repo).toLowerCase().includes(q)));$('pairs').replaceChildren();$('empty').hidden=list.length!==0;
 for(const p of list){const card=el('article','pair-card '+(isIssue(p)?'attention':''));const top=el('div','card-top');top.append(el('span','repo-icon','⌘'),el('h2','',p.github_repo.split('/').pop()),badge(p));card.append(top);const repos=el('div','repo-paths');repos.append(el('p','', 'GitHub  '+p.github_repo),el('p','', 'NAS       '+p.gitea_repo));card.append(repos);const meta=el('div','card-meta');meta.append(el('span','direction',directions[p.direction]),el('span','',p.enabled?'자동 · '+p.interval+'분마다':'자동 실행 꺼짐'));card.append(meta);
 const status=el('div','card-status');if(p.busy||p.queued){status.append(el('div','activity'),el('span','',p.queued?'다른 저장소 작업이 끝나면 시작해요':'저장소를 처리하고 있어요'))}else{status.append(el('span','',p.error||(p.phase==='conflict'?'갈라진 작업이 있어요. 상세에서 확인해 주세요':p.phase==='pending'?'반영할 새 변경이 있어요':p.checked?'두 저장소 확인을 마쳤어요':'연결 확인부터 시작하세요')))}card.append(status);const times=el('div','card-times');times.append(el('span','', '최근 확인  '+timeText(p.last)));if(p.enabled)times.append(el('span','', '다음 확인  '+timeText(p.next)));card.append(times,actionButtons(p));$('pairs').append(card)}
}
function draw(s){state=s;csrf=s.csrf;const active=s.pairs.filter(p=>!p.archived);$('countAll').textContent=active.length;$('countHealthy').textContent=active.filter(p=>p.checked&&!p.busy&&!p.queued&&!isIssue(p)&&p.phase==='healthy').length;$('countBusy').textContent=active.filter(p=>p.busy||p.queued).length;$('countIssues').textContent=active.filter(isIssue).length;$('updated').textContent='마지막 화면 갱신 '+new Date().toLocaleTimeString('ko-KR');if(s.gitea_user&&!$('accountsModal').open)$('giteaUser').value=s.gitea_user;$('ghState').textContent=s.github_saved?'연결 키 저장됨':'미연결';$('gtState').textContent=s.gitea_saved?'연결 키 저장됨':'미연결';$('ghState').className='tag '+(s.github_saved?'healthy':'');$('gtState').className='tag '+(s.gitea_saved?'healthy':'');if(s.github_saved)$('gh').placeholder='저장됨 · 변경할 때만 새 키 입력';if(s.gitea_saved)$('gt').placeholder='저장됨 · 변경할 때만 새 키 입력';$('detectNAS').disabled=!secure||s.detecting||pending.has('detect');$('detectStatus').textContent=s.detect_message||'';if(detectVersion!==(s.detect_version||0)){const first=detectVersion===-1;detectVersion=s.detect_version||0;const list=$('giteaCandidates');list.replaceChildren();for(const c of(s.nas_connections||[])){const o=el('option');o.value=c.url;o.label=c.kind;list.append(o)}if(first)$('giteaEndpoint').value=s.gitea_base||'';else if(!$('accountsModal').open)$('giteaEndpoint').value=s.gitea_base||'';updateTokenLink()}$('save').disabled=!secure||pending.has('save')||s.discovering||s.pairs.some(p=>p.busy||p.queued);$('refreshRepos').disabled=!secure||s.discovering||pending.has('discover')||!s.github_saved||!s.gitea_saved;$('repoListStatus').textContent=s.discovering?'저장소 목록을 불러오고 있어요':s.discovery_error||s.discovery_notice||('GitHub '+s.repos.github.length+'개 · NAS '+s.repos.gitea.length+'개');$('addPair').disabled=!secure||pending.has('add')||!$('ghRepo').value||!$('gtRepo').value;if(repoVersion!==s.repo_version){repoVersion=s.repo_version;renderRepoOptions()};renderPairs();if($('detailModal').open)renderDetail(false);if(s.role==='viewer'){for(const id of ['navAccounts','openAdd','navDiagnostics','addPair','save','savePair','archivePair','deletePair']){const n=$(id);if(n)n.disabled=true}for(const b of $('pairs').querySelectorAll('button'))if(b.textContent!=='상세 보기')b.disabled=true}}
function renderRepoOptions(){if(!state)return;for(const [side,prefix]of[['github','gh'],['gitea','gt']]){const list=$(prefix+'Repo'),old=list.value,q=$(prefix+'Filter').value.toLowerCase().trim();list.replaceChildren();const blank=el('option','', '저장소를 선택하세요');blank.value='';list.append(blank);for(const repo of state.repos[side]){if(q&&!repo.full_name.toLowerCase().includes(q))continue;const used=state.pairs.some(p=>!p.archived&&(side==='github'?p.github_repo:p.gitea_repo).toLowerCase()===repo.full_name.toLowerCase());const o=el('option','',repo.full_name+(used?' · 연결됨':repo.archived?' · 읽기 전용':''));o.value=repo.full_name;o.disabled=used;list.append(o)}list.value=old;if(list.selectedIndex<0)list.value=''}$('addPair').disabled=!secure||pending.has('add')||!$('ghRepo').value||!$('gtRepo').value}
async function refresh(){if(refreshing)return;refreshing=true;const seq=++refreshSeq;try{const s=await api('status');if(seq===refreshSeq)draw(s)}catch(e){note(e.message,true)}finally{refreshing=false}}
async function action(name,body={}){const key=body.id||name;if(pending.has(key))return false;pending.add(key);refreshSeq++;if(state)draw(state);try{const result=await api(name,body);if(name==='delete'){if($('detailModal').open)$('detailModal').close();note(result.warning||'연결과 내부 캐시를 제거했어요. 원본 저장소는 그대로예요',!!result.warning)}else if(name==='save'){$('gh').value='';$('gt').value='';note('연결 키를 저장했어요. 저장소 목록을 불러오고 있어요')}else if(name==='add'){$('addModal').close();note('저장소를 연결했어요. 카드에서 연결 확인을 눌러 주세요')}else if(name==='update'){note('설정을 저장했어요. 다시 확인한 뒤 자동 실행을 켜 주세요')}else if(name==='archive'){$('detailModal').close();note('연결을 보관했어요. 저장소 코드는 그대로예요')}else{note({check:'변경 없이 확인을 시작했어요',sync:'동기화를 요청했어요',start:'자동 실행을 켰어요',pause:'일시정지를 요청했어요',restore:'연결을 복원했어요',discover:'저장소 목록을 새로 불러오고 있어요',detect:'NAS에서 Gitea 연결을 확인하고 있어요. 토큰은 전송하지 않아요'}[name]||'저장했어요')}return true}catch(e){note(e.message,true);return false}finally{pending.delete(key);refreshing=false;await refresh()}}
function openDialog(id){clearMessage(id==='usersModal'?'usersMessage':id==='accountsModal'?'accountMessage':id==='addModal'?'addMessage':'detailMessage');$(id).showModal()}
function openAccounts(){openDialog('accountsModal')}
function openAdd(){if(!state||!state.github_saved||!state.gitea_saved){openAccounts();note('계정을 먼저 연결하면 저장소 목록에서 고를 수 있어요');return}openDialog('addModal');renderRepoOptions();if(!state.repos.github.length&&!state.discovering)action('discover')}
function openDetail(id){detailId=id;openDialog('detailModal');renderDetail(true)}
function renderDetail(initial){const p=state.pairs.find(x=>x.id===detailId);if(!p){$('detailModal').close();return}$('detailTitle').textContent=p.github_repo.split('/').pop();$('detailStatus').replaceChildren(badge(p),el('span','muted',p.error||'최근 확인 '+timeText(p.last)));$('detailLinks').replaceChildren();for(const [text,url]of[['GitHub 저장소 ↗','https://github.com/'+p.github_repo],['NAS 저장소 ↗',(state.gitea_base||'')+'/'+p.gitea_repo]]){const a=el('a','',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';$('detailLinks').append(a)}if(initial){$('editDirection').value=p.direction;$('editInterval').value=String(p.interval)}const locked=p.busy||!!p.queued||p.archived||pending.has(p.id);$('savePair').disabled=locked||!secure;$('editDirection').disabled=locked;$('editInterval').disabled=locked;$('archivePair').disabled=p.busy||!!p.queued||pending.has(p.id)||!secure;$('deletePair').disabled=p.busy||!!p.queued||pending.has(p.id)||!secure;$('archivePair').textContent=p.archived?'연결 복원':'연결 보관';$('detailPlan').replaceChildren();if(!p.plan.length)$('detailPlan').append(el('p','muted','연결 확인을 실행하면 브랜치와 태그별 결과가 나와요'));for(const r of p.plan){const row=el('div','ref '+r.status);row.append(el('b','',r.ref),el('span','',r.direction),el('p','',r.detail));$('detailPlan').append(row)}$('detailEvents').replaceChildren();for(const e of p.events){const li=el('li');li.append(el('time','',timeText(e.at)),el('span','',e.message));$('detailEvents').append(li)}}
async function diagnostics(){const list=$('diagnosticsResults');list.replaceChildren(el('p','muted','NAS 실행 상태를 확인하고 있어요'));$('retryDiagnostics').disabled=true;try{const data=await api('diagnostics');list.replaceChildren();for(const c of data.checks){const row=el('div','ref');row.append(el('b','',c.title),el('span','tag '+(c.ok?'healthy':'error'),c.ok?'확인됨':'확인 필요'),el('p','',c.detail));list.append(row)}}catch(e){list.replaceChildren(el('p','error',e.message))}finally{$('retryDiagnostics').disabled=false}}
$('navDiagnostics').addEventListener('click',()=>{$('diagnosticsModal').showModal();diagnostics()});$('retryDiagnostics').addEventListener('click',diagnostics);
$('openAdd').addEventListener('click',openAdd);$('navAccounts').addEventListener('click',openAccounts);$('navDashboard').addEventListener('click',()=>{filter='all';setFilterUI();renderPairs()});$('search').addEventListener('input',renderPairs);
function setFilterUI(){for(const b of document.querySelectorAll('[data-filter]'))b.classList.toggle('selected',b.dataset.filter===filter)}
for(const b of document.querySelectorAll('[data-filter]'))b.addEventListener('click',()=>{filter=b.dataset.filter;setFilterUI();renderPairs()});
for(const b of document.querySelectorAll('dialog .close'))b.addEventListener('click',()=>b.closest('dialog').close());
for(const id of ['ghFilter','gtFilter'])$(id).addEventListener('input',renderRepoOptions);
for(const id of ['ghRepo','gtRepo'])$(id).addEventListener('change',()=>{$('addPair').disabled=!secure||pending.has('add')||!$('ghRepo').value||!$('gtRepo').value});
$('detectNAS').addEventListener('click',()=>action('detect'));
$('refreshRepos').addEventListener('click',()=>action('discover'));
$('save').addEventListener('click',()=>{if(!$('consent').checked){note('연결 키를 NAS에 저장하는 항목을 체크해 주세요',true);return}action('save',{github_token:$('gh').value.trim(),gitea_token:$('gt').value.trim(),gitea_base:$('giteaEndpoint').value,gitea_user:$('giteaUser').value.trim(),consent:true})});
$('addPair').addEventListener('click',()=>action('add',{github_repo:$('ghRepo').value,gitea_repo:$('gtRepo').value,direction:$('newDirection').value}));
$('savePair').addEventListener('click',()=>action('update',{id:detailId,direction:$('editDirection').value,interval:Number($('editInterval').value)}));
$('archivePair').addEventListener('click',()=>{const p=state.pairs.find(x=>x.id===detailId);if(p)action(p.archived?'restore':'archive',{id:p.id})});
async function boot(){if(!secure){for(const id of ['gh','gt','consent','save'])$(id).disabled=true;note('HTTPS 주소로 접속해 주세요',true);return}await refresh();setInterval(refresh,4000)}boot();

function updateTokenLink(){const a=$('giteaTokenLink');try{const u=new URL($('giteaEndpoint').value);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error();u.pathname='/user/settings/applications';a.href=u.href;a.hidden=false}catch{a.removeAttribute('href');a.hidden=true}}
$('giteaEndpoint').addEventListener('input',updateTokenLink);

async function removePair(id){const p=state?.pairs.find(x=>x.id===id);if(!p||p.busy||p.queued||pending.has(id))return;if(!window.confirm('이 동기화 연결을 제거할까요?\nGitHub: '+p.github_repo+'\nGitea: '+p.gitea_repo+'\n\n이 앱의 연결 설정·내부 캐시·확인 기록을 삭제해요. GitHub/Gitea의 원본 저장소는 삭제하지 않아요. 다시 등록하면 이전 삭제 감지 기록 없이 새로 확인해야 해요.'))return;await action('delete',{id,consent:true})}
$('deletePair').addEventListener('click',()=>removePair(detailId));

let usersBusy=false;
async function loadUsers(){if(state?.role!=='admin')return;const users=await api('auth/users');$('usersList').replaceChildren();for(const u of users){const row=el('div','ref');row.append(el('b','',u.username),el('span','',u.role==='admin'?'관리자':'조회자'),el('p','',u.disabled?'비활성':'활성'));if(u.username!==state.user){row.append(button(u.disabled?'활성화':'비활성화',()=>manageUser(u.disabled?'enable':'disable',u.username)));row.append(button('비밀번호 재설정',()=>manageUser('password',u.username)));row.append(button('계정 삭제',()=>manageUser('delete',u.username)))}$('usersList').append(row)}}
async function openUsers(){openDialog('usersModal');$('signedIn').textContent=(state?.user||'')+' · '+(state?.role==='admin'?'관리자':'조회자');$('adminUserPanel').hidden=state?.role!=='admin';try{await loadUsers()}catch(e){$('usersMessage').textContent=e.message}}
async function manageUser(operation,username){if(usersBusy)return;if(['delete','disable','password'].includes(operation)&&!confirm(username+' 계정의 '+({delete:'삭제',disable:'비활성화',password:'비밀번호 재설정'}[operation])+'을 진행할까요? 활성 로그인도 종료돼요.'))return;usersBusy=true;try{await api('auth/users',{operation,username,password:$('newUserPassword').value,current_password:$('manageCurrent').value,role:$('newUserRole').value});$('usersMessage').textContent='계정 변경을 저장했어요';await loadUsers()}catch(e){$('usersMessage').textContent=e.message}finally{usersBusy=false;$('manageCurrent').value='';$('newUserPassword').value=''}}
$('navUsers').addEventListener('click',openUsers);
$('logout').addEventListener('click',async()=>{try{await api('auth/logout',{});location.replace('index.cgi')}catch(e){note(e.message,true)}});
$('createUser').addEventListener('click',()=>manageUser('create',$('newUsername').value.trim()));
$('changeOwn').addEventListener('click',async()=>{if(usersBusy)return;if($('ownNew').value!==$('ownConfirm').value){$('usersMessage').textContent='새 비밀번호 확인이 일치하지 않아요';return}usersBusy=true;try{await api('auth/password',{current_password:$('ownCurrent').value,password:$('ownNew').value});location.replace('index.cgi')}catch(e){$('usersMessage').textContent=e.message}finally{usersBusy=false;for(const id of ['ownCurrent','ownNew','ownConfirm'])$(id).value=''}});
$('usersModal').addEventListener('close',()=>{for(const id of ['ownCurrent','ownNew','ownConfirm','manageCurrent','newUserPassword'])$(id).value=''});
